Add simple sanity check (#175)
* Add simple sanity check

* removing unnecessary exit code checks

diff --git a/config/job.template b/config/job.template
--- a/config/job.template
+++ b/config/job.template
@@ -100,6 +100,15 @@ tail -n +2 $results_dir/job.yaml
 echo "Results directory:"
 echo "  $results_dir"
 
+# Run a sanity check on the nodes to ensure ROCm is working correctly.
+sanity_check_script="$omnihub_dir/scripts/sanity-check.sh"
+srun -N$SLURM_NNODES -n$SLURM_NNODES apptainer run $shared_dir/apptainer/omnihub.$gpu_arch.$rocm_version.sif /bin/bash -c "$sanity_check_script"
+# Check if the sanity check script ran successfully
+if [ $? -ne 0 ]; then
+    echo "Error: Sanity check failed. Exiting."
+    exit 1
+fi
+
 # Run the system information script inside the Apptainer container
 apptainer run $shared_dir/apptainer/omnihub.$gpu_arch.$rocm_version.sif /bin/bash -c "$omnihub_dir/scripts/generate-sysinfo.sh $results_dir"
 
